# A Whirlwind Tutorial of the Key Concepts in Python You'll Need

Behind the notes below is it introduced the key concepts that you will need to know prior to doing your homework assignments. If you have experience with python in the past, and the below should be relatively familiar. You may yet be surprised by some of the interesting behavior that python produces.

Some of the imports we'll commonly be using:

In [1]:
import os
# our main library for numerical computation
import numpy as np
# matplotlib will plot for us
import matplotlib.pyplot as plt
# inline plots with matplotlib:
%matplotlib inline
from timeit import timeit

Defining variables and data types:

In [2]:
a = 2
print(a)
print(type(a))
print(id(a))

2
<class 'int'>
137347537568016


In [3]:
b = 2.0
print(b)
print(type(b))
print(id(b))

2.0
<class 'float'>
137344635810224


In [4]:
mylist = [1, 2, 3]
print(mylist)
print(type(mylist))
print(id(mylist))

[1, 2, 3]
<class 'list'>
137344635491776


In [5]:
mystring = "Hello World"
print(mystring)
print(type(mystring))
print(id(mystring))

Hello World
<class 'str'>
137344634084976


Mutability vs immutability in Python:

In [6]:
print(a)
print(id(a))
a = 3
print(a)
print(id(a))

2
137347537568016
3
137347537568048


Note that the address that `a` points to has changed. (Explanation on iPad).

In [7]:
print(b)
print(id(b))
b = 3.0
print(b)
print(id(b))

2.0
137344635810224
3.0
137344635812816


Many of the primitive data types in Python are immutable. Are strings mutable?

In [8]:
print(mystring)
print(id(mystring))
print(mystring[0])

Hello World
137344634084976
H


In [9]:
# assignment to a string example case: 
# mystring[0] = 'h' # Not gonna work 

TypeError: 'str' object does not support item assignment

This error occurs because the native string type is *not* mutable, there is no way to change the elements in place, you'll need to create a new string for that.

In [10]:
print(mylist)
print(id(mylist))
mylist[0] = 5
print(mylist)
print(id(mylist))

[1, 2, 3]
137344635491776
[5, 2, 3]
137344635491776


Lists, Dictionaries, and Sets are three important data types that are mutable. What's the difference between a List and a Set? 

It's important to understand what is mutable and what is immutable in python as it affects how we treat data we pass to our functions. You'll likely care a lot about this when we work with point clouds.

In [13]:
def foo(a):
    b = a
    print(b)
    print(id(b))
    return b

In [14]:
a = 2
print(a)
print(id(a))
print('---')
a = foo(a)
print('---')
print(a)
print(id(a))

2
137347537568016
---
2
137347537568016
---
2
137347537568016


In [19]:
def bar(list):
    list[0] = 5
    print(list)
    print(id(list))
    return list

mylist = [1, 2, 3]
print(mylist)
print(id(mylist))
print('---')
mylist = bar(mylist)
print('---')
print(mylist)
print(id(mylist))

[1, 2, 3]
137344635491776
---
[5, 2, 3]
137344635491776
---
[5, 2, 3]
137344635491776


The above is important! If you have learned about 'scopes' before, you may be surprised by this behavior. Despite changing the lists value inside the scope of the function, the value also changed outside. This is a very important feature of mutable data types. If you're not careful, this may become a headache later on.

A common mistake we see is multiple assignments in a single line when a variable is mutable.

In [20]:
c = d = [1, 2, 3]
print(c)
print(d)
print(id(c))
print(id(d))

[1, 2, 3]
[1, 2, 3]
137344621810304
137344621810304


In [21]:
d[0] = 3
print(c)
print(d)
print(id(c))
print(id(d))

[3, 2, 3]
[3, 2, 3]
137344621810304
137344621810304


This does not happen with immutable variables.

In [22]:
e = f = 2
print(id(e))
print(id(f))
f = 3
print(e)
print(f)
print(id(e))
print(id(f))

137347537568016
137347537568016
2
3
137347537568016
137347537568048


There are only 3 really important concepts up to this point you should really know:

1- How to create variables (we'll mostly be working with scalars, vectors, and matrices -- you'll see soon)
2- Understanding mutability vs immutability
3- How to write functions

Python is a very powerful `object oriented` programming language. In fact, everything in python is an Object. Don't believe me?

In [23]:
a = -2
print(type(a))
print(a.__abs__())
print(abs(a))

<class 'int'>
2
2


In [24]:
def foo(a):
    return a ** 2

print(type(foo))

<class 'function'>


In this class, we'll take care of the vast majority of the object-orientedness of the programs. You'll mostly be writing functions. Thus, you won't really need to mastery of OOP to perform well in the class. However, we very strongly encourage you to self-educate on OOP as a programming paradigm and the richness of OOP in Python.

# Numpy

With the introductions out of the way, let's dive into the meat of todays lecture. Libraries that speed up linear algebra calculations are a staple if you work in fields like robotics, machine learning, data science, or deep learning.  NumPy, short for Numerical Python, is perhaps the most famous of the lot, and chances are you've already used it. It is important to understand that Numpy is optimized for CPU computation. Libraries such as Torch and Jax further accelerate linear algebra using GPUs and a very easy to learn if you have a solid foundation in numpy.

In [25]:
# let's define a vector in numpy
a = np.array([1., 2., 3.])
print(a)
print(type(a))
print(a.shape) # this is the `dimensions` of the array
print(a.dtype) # this is the type of the array

[1. 2. 3.]
<class 'numpy.ndarray'>
(3,)
float64


Note the size of the vector. Any 1D array can be represented as (N, ) and has the flexibility to be treat as a column or row vector depending on the context. If you need a specific shape, you can fix this by doing the following:

In [26]:
col_vec = a[:, np.newaxis]
row_vec = a[np.newaxis, :]
print(col_vec.shape)
print(row_vec.shape)

(3, 1)
(1, 3)


You can also achieve the same effect by doing:

In [27]:
col_vec2 = a.reshape((3, 1))
print(col_vec2.shape)

(3, 1)


Now that we know how to define vectors, let's take a look at matrices:

In [28]:
mata = np.array([[1., 2., 3.], [4., 5., 6.]])
print(mata.shape)

a = np.array([1., 2., 3.])
print(a.shape)

(2, 3)
(3,)


Now let's take a look at matrix multiplication:

In [30]:
prod = mata.dot(a)
print(prod)
print(prod.shape)
print(id(prod))

prod2 = mata @ a
print(prod2)
print(prod2.shape)
print(id(prod2))

[14. 32.]
(2,)
137344621736176
[14. 32.]
(2,)
137344621730416


Note how numpy figured out to treat `a` as a column vector for the multiplication. This is due to *broadcasting* rules that we'll get into shortly.

The `@` operator is a matrix multiplication when there is a matrix involved; however, it also does dot (inner) products. This is the default behavior when `@` is used between two vectors:

In [34]:
a = np.array([1., 2., 3.])
# a = a.reshape((3,1))
b = np.array([1., 2., 3.])
# b = b.reshape((1,3))

print(a @ b)

14.0


So far, you've learned how to manually define vectors and matrices. We can also use a few handy tools to help us define some of the more common vectors and matrices:

In [35]:
print(np.linspace(0, 10, 11))
print(np.eye(3))
print(np.zeros((3, 3)))
print(np.ones((3, 3)))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Vectorization in Numpy

Now that you've learned the basics of matrix algebra, let's talk about some of the advantages of using numpy of vanilla python. First item is vectorization. 

Vectorization is a powerful ability within NumPy to express operations as occurring on entire arrays rather than their individual elements. When looping over an array or any data structure in Python, there’s a lot of overhead involved. Vectorized operations in NumPy delegate the looping internally to highly optimized C and Fortran functions, making for cleaner and faster Python code.

Let's see a simple example:

Write a function that takes in a 1-dimensional vector of True or False values and returns the number of False to True transitions:

In [36]:
# Brute force for loop method:
# Count the number of transitions from False to True in a boolean array using a for loop

np.random.seed(400)
x = np.random.choice([False, True], size = 100000)

def count_transitions(x):
    count = 0
    for i in range(len(x)-1):
        if x[i] == False and x[i+1] == True:
            count += 1
    return count

print(count_transitions(x))

25191


In [42]:
# More efficient methods:

# approach 1: use logical_and to find all the places where x[i] == False and x[i+1] == True
print(np.sum(np.logical_and(x[:-1] == False, x[1:] == True)))

# approach 2: differences -- np.diff to find all the places where x[i+1] - x[i] == 1
print(np.sum(np.diff(x.astype(int)) == 1))

# approach 3: to use count_nonzero to count all the places where x[i] == False and x[i+1] == True
print(np.count_nonzero(np.diff(x.astype(int)) == 1))

25191
25191
25191


All our methods give the same answer, but how fast are they?

In [45]:
# benchmarking the three methods:
num = 10
t1 = timeit('count_transitions(x)', number=num, globals=globals())
t2 = timeit('np.sum(np.logical_and(x[:-1] == False, x[1:] == True))', number=num, globals=globals())
t3 = timeit('np.sum(np.diff(x.astype(int)) == 1)', number=num, globals=globals())
t4 = timeit('np.count_nonzero(np.diff(x.astype(int)) == 1)', number=num, globals=globals())

print("Speed defference: for loop vs logical and: {:.1f}x".format(t1 / t2))
print("Speed defference: for loop vs diff: {:.1f}x".format(t1 / t3))
print("Speed defference: for loop vs count_nonzero: {:.1f}x".format(t1 / t4))

Speed defference: for loop vs logical and: 278.4x
Speed defference: for loop vs diff: 823.1x
Speed defference: for loop vs count_nonzero: 1981.8x


This should tell you that whenever you can, you should avoid using for loops and instead focus on vectorization. In addition to the in-built functionalities of numpy, we can also vectorize entire functions. Here is an example:

In [ ]:
# example of vectorizing a function using numpy
def f(x):
    if x < 0:
        return 0
    else:
        return x

f_vec = np.vectorize(f)

# try your own functions

# benchmark the three methods


This example shows you how well-implemented vectorization can easily surpass naive approaches.

## Broadcasting as a Form of Vectorization

Broadcasting is a powerful form of vectorization that you should master for effective use of Numpy. So what is broadcasting? First an example:

In [46]:
a = np.array([1., 2., 3.])
b = np.array([1])

print(a * b)

[1. 2. 3.]


What do you expect the output of the summation to be?

In [47]:
print(a + b)

[2. 3. 4.]


In [56]:
c = np.array([[1., 2., 3.], [4., 5., 6.]])
d = np.array([[1], [2]])
# d = np.array([1,2]) would not work

print(c.shape)
print(d.shape)

(2, 3)
(2, 1)


What are the expected behaviors for summation and multiplication?

In [57]:
print(c * d)
print(c + d)

[[ 1.  2.  3.]
 [ 8. 10. 12.]]
[[2. 3. 4.]
 [6. 7. 8.]]


Broadcasting allows numpy to infer and extend arrays to match sizes and produce desired outputs without the need for additional specification or usage of for loops from us. There are rules/constraints that arrays have to meet for broadcasting to apply. Please review the documentation.

Broadcasting in action: Return the index of the closest point (in Euclidean distance) of the array `a` given a query point 'b':

In [58]:
x = np.array([1., 2., 3.])
y = np.random.rand(10000, 3)


In [61]:
# naive approach, write a for loop to compute the distance given a vector and an array of vectors
def distance(x, y):
    dist = np.zeros(y.shape[0])
    for i in range(y.shape[0]):
        dist[i] = np.sqrt(np.sum((x - y[i, :]) ** 2))
    return dist

t1 = timeit('np.argmin(distance(x, y))', number=num, globals=globals())

# now lets use broadcasting to do the same thing
t2 = timeit('np.argmin(np.sqrt(np.sum((x - y) ** 2, axis=1)))', number=num, globals=globals())

# now lets use einsum to do the same thing
t3 = timeit('np.argmin(np.sqrt(np.einsum("ij,ij->i", x - y, x - y)))', number=num, globals=globals())

print('Speed difference: for loop vs broadcasting: {:.1f}x'.format(t1 / t2))
print('Speed difference: for loop vs einsum: {:.1f}x'.format(t1 / t3))

Speed difference: for loop vs broadcasting: 233.8x
Speed difference: for loop vs einsum: 191.1x


Let's try a bit of image manipulation: I want to convert an RGB image into a grayscale image without any for loops:

In [ ]:
from PIL import Image
gray_weights = np.array([0.2125, 0.7154, 0.0721])

image_pil = Image.open('mich_logo.jpg')
image_pil.show()

image_np = np.array(image_pil)
print(image_np.shape)

# numpy with broadcasting
image_gs_mean = image_np @ gray_weights

# numpy einsum
image_gs_ein = np.einsum('ijk,k->ij', image_np, gray_weights)

image_pil_gs_mean = Image.fromarray(image_gs_mean)
image_pil_gs_ein = Image.fromarray(image_gs_ein)

image_pil_gs_mean.show()
image_pil_gs_ein.show()
